### ISSUE TITLE
docs: Document facades we provide 

### ISSUE THREAD

**Issue by wlee221** [aws-amplify/amplify-ui#664]
Related: #254

We now provide public hooks/services for Authenticator: #532 (React), #588 (Vue), and #627 (Angular). We should document facades we provide. 

We'll need to be careful to focus on actual use cases though, so that it's not just a giant table.

### TODOs

- [x] Create examples matching https://codesandbox.io/s/change-your-layout-rh4z9?file=/src/Login.js
- [x] Document `Authenticator.Provider` for React
- [x] Document `useAuthenticator` hooks & services

**Comment by ericclemmons** [comment]
https://codesandbox.io/s/change-your-layout-rh4z9?file=/src/App.js is a great example for React.

**Comment by wlee221** [comment]
It's been quite long since I last tackled this. 

I think it'd be good to be a little verbose in documentation and provide `tabs` of facadades we provide:

```
tab 1 (context) - user, route, error, isPending, codeDeliveryDetails
tab 2 (transitions) - to* hooks and `signOut`
tab 3 (forms) - updateForm, submitForm
```
